# Generated by Django 4.0.2 on 2022-10-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='daejeonfood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('업소명', models.TextField()),
                ('도로명주소', models.TextField()),
                ('소재지주소', models.TextField()),
                ('지정일자', models.BigIntegerField()),
                ('음식의유형', models.TextField()),
                ('주된음식종류', models.TextField()),
                ('전화번호', models.TextField()),
            ],
        ),
    ]
