# Generated by Django 4.0.2 on 2022-11-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daejeonfood',
            old_name='id',
            new_name='번호',
        ),
    ]
